// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteResourcesByIdData, DeleteResourcesByIdErrors, DeleteResourcesByIdResponses, DeleteTemplatesByIdData, DeleteTemplatesByIdErrors, DeleteTemplatesByIdResponses, GetResourcesByIdData, GetResourcesByIdErrors, GetResourcesByIdResponses, GetResourcesData, GetResourcesErrors, GetResourcesResponses, GetTemplatesByIdData, GetTemplatesByIdErrors, GetTemplatesByIdResponses, GetTemplatesData, GetTemplatesErrors, GetTemplatesResponses, PostResourcesData, PostResourcesErrors, PostResourcesResponses, PostTemplatesData, PostTemplatesErrors, PostTemplatesResponses, PutResourcesByIdData, PutResourcesByIdErrors, PutResourcesByIdResponses, PutTemplatesByIdData, PutTemplatesByIdErrors, PutTemplatesByIdResponses } from './types.gen';
import { zDeleteResourcesByIdPath, zDeleteTemplatesByIdPath, zGetResourcesByIdPath, zGetResourcesByIdResponse, zGetResourcesResponse, zGetTemplatesByIdPath, zGetTemplatesByIdResponse, zGetTemplatesResponse, zPostResourcesBody, zPostTemplatesBody, zPutResourcesByIdBody, zPutResourcesByIdPath, zPutTemplatesByIdBody, zPutTemplatesByIdPath } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List all resources
 *
 * Get a list of all resources in the collection
 */
export const getResources = <ThrowOnError extends boolean = false>(options?: Options<GetResourcesData, ThrowOnError>): RequestResult<GetResourcesResponses, GetResourcesErrors, ThrowOnError> => (options?.client ?? client).get<GetResourcesResponses, GetResourcesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetResourcesResponse.parseAsync(data),
    url: '/resources',
    ...options
});

/**
 * Create a new resource
 *
 * Add a new resource to the collection
 */
export const postResources = <ThrowOnError extends boolean = false>(options: Options<PostResourcesData, ThrowOnError>): RequestResult<PostResourcesResponses, PostResourcesErrors, ThrowOnError> => (options.client ?? client).post<PostResourcesResponses, PostResourcesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostResourcesBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/resources',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a resource
 *
 * Remove a resource from the collection
 */
export const deleteResourcesById = <ThrowOnError extends boolean = false>(options: Options<DeleteResourcesByIdData, ThrowOnError>): RequestResult<DeleteResourcesByIdResponses, DeleteResourcesByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteResourcesByIdResponses, DeleteResourcesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zDeleteResourcesByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/resources/{id}',
    ...options
});

/**
 * Get a resource by ID
 *
 * Get detailed information about a single resource
 */
export const getResourcesById = <ThrowOnError extends boolean = false>(options: Options<GetResourcesByIdData, ThrowOnError>): RequestResult<GetResourcesByIdResponses, GetResourcesByIdErrors, ThrowOnError> => (options.client ?? client).get<GetResourcesByIdResponses, GetResourcesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetResourcesByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetResourcesByIdResponse.parseAsync(data),
    url: '/resources/{id}',
    ...options
});

/**
 * Update a resource
 *
 * Update an existing resource's information
 */
export const putResourcesById = <ThrowOnError extends boolean = false>(options: Options<PutResourcesByIdData, ThrowOnError>): RequestResult<PutResourcesByIdResponses, PutResourcesByIdErrors, ThrowOnError> => (options.client ?? client).put<PutResourcesByIdResponses, PutResourcesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPutResourcesByIdBody,
        path: zPutResourcesByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/resources/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all templates
 *
 * Get a list of all templates in the collection
 */
export const getTemplates = <ThrowOnError extends boolean = false>(options?: Options<GetTemplatesData, ThrowOnError>): RequestResult<GetTemplatesResponses, GetTemplatesErrors, ThrowOnError> => (options?.client ?? client).get<GetTemplatesResponses, GetTemplatesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetTemplatesResponse.parseAsync(data),
    url: '/templates',
    ...options
});

/**
 * Create a new template
 *
 * Add a new template to the collection
 */
export const postTemplates = <ThrowOnError extends boolean = false>(options: Options<PostTemplatesData, ThrowOnError>): RequestResult<PostTemplatesResponses, PostTemplatesErrors, ThrowOnError> => (options.client ?? client).post<PostTemplatesResponses, PostTemplatesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPostTemplatesBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/templates',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a template
 *
 * Remove a template from the collection
 */
export const deleteTemplatesById = <ThrowOnError extends boolean = false>(options: Options<DeleteTemplatesByIdData, ThrowOnError>): RequestResult<DeleteTemplatesByIdResponses, DeleteTemplatesByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteTemplatesByIdResponses, DeleteTemplatesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zDeleteTemplatesByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/templates/{id}',
    ...options
});

/**
 * Get a template by ID
 *
 * Get detailed information about a single template
 */
export const getTemplatesById = <ThrowOnError extends boolean = false>(options: Options<GetTemplatesByIdData, ThrowOnError>): RequestResult<GetTemplatesByIdResponses, GetTemplatesByIdErrors, ThrowOnError> => (options.client ?? client).get<GetTemplatesByIdResponses, GetTemplatesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetTemplatesByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetTemplatesByIdResponse.parseAsync(data),
    url: '/templates/{id}',
    ...options
});

/**
 * Update a template
 *
 * Update an existing template's information
 */
export const putTemplatesById = <ThrowOnError extends boolean = false>(options: Options<PutTemplatesByIdData, ThrowOnError>): RequestResult<PutTemplatesByIdResponses, PutTemplatesByIdErrors, ThrowOnError> => (options.client ?? client).put<PutTemplatesByIdResponses, PutTemplatesByIdErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zPutTemplatesByIdBody,
        path: zPutTemplatesByIdPath,
        query: z.never().optional()
    }).parseAsync(data),
    url: '/templates/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
