// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:9136/' | (string & {});
};

export type ResourcesCreateResourceRequestDto = {
    description?: string;
    name: string;
    price: number;
    quantity: number;
    unit: string;
};

export type ResourcesResourceJsonResponseDto = {
    base_quantity: number;
    base_unit: string;
    created_at: string;
    description: string;
    id: number;
    name: string;
    price: number;
    updated_at: string;
};

export type ResourcesUpdateResourceRequestDto = {
    description?: string;
    id: number;
    name: string;
    price: number;
    quantity: number;
    unit: string;
};

export type TemplatesCreateTemplateRequestDto = {
    description: string;
    difficulty: number;
    name: string;
    quantity: number;
    resources: Array<TemplatesResourceRefDto>;
    steps: Array<TemplatesStepDto>;
    unit: string;
};

export type TemplatesResourceRefDto = {
    quantity: number;
    resource_id: number;
    unit: string;
};

export type TemplatesResourceRefResponseDto = {
    quantity: number;
    resource_id: number;
    unit: string;
};

export type TemplatesStepDto = {
    instructions: string;
    name: string;
};

export type TemplatesStepJsonResponseDto = {
    instructions: string;
    name: string;
    order: number;
};

export type TemplatesTemplateJsonResponseDto = {
    description: string;
    difficulty: number;
    id: number;
    name: string;
    quantity: number;
    resources: Array<TemplatesResourceRefResponseDto>;
    steps: Array<TemplatesStepJsonResponseDto>;
    unit: string;
};

export type TemplatesTemplateListJsonResponseDto = {
    description: string;
    id: number;
    name: string;
};

export type TemplatesUpdateTemplateRequestDto = {
    description: string;
    difficulty: number;
    id: number;
    name: string;
    quantity: number;
    resources: Array<TemplatesResourceRefDto>;
    steps: Array<TemplatesStepDto>;
    unit: string;
};

export type GetResourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/resources';
};

export type GetResourcesErrors = {
    /**
     * internal error
     */
    500: string;
};

export type GetResourcesError = GetResourcesErrors[keyof GetResourcesErrors];

export type GetResourcesResponses = {
    /**
     * OK
     */
    200: Array<ResourcesResourceJsonResponseDto>;
};

export type GetResourcesResponse = GetResourcesResponses[keyof GetResourcesResponses];

export type PostResourcesData = {
    /**
     * Resource object
     */
    body: ResourcesCreateResourceRequestDto;
    path?: never;
    query?: never;
    url: '/resources';
};

export type PostResourcesErrors = {
    /**
     * invalid request
     */
    400: string;
};

export type PostResourcesError = PostResourcesErrors[keyof PostResourcesErrors];

export type PostResourcesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteResourcesByIdData = {
    body?: never;
    path: {
        /**
         * Resource ID
         */
        id: number;
    };
    query?: never;
    url: '/resources/{id}';
};

export type DeleteResourcesByIdErrors = {
    /**
     * invalid id
     */
    400: string;
    /**
     * resource not found
     */
    404: string;
    /**
     * internal error
     */
    500: string;
};

export type DeleteResourcesByIdError = DeleteResourcesByIdErrors[keyof DeleteResourcesByIdErrors];

export type DeleteResourcesByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetResourcesByIdData = {
    body?: never;
    path: {
        /**
         * Resource ID
         */
        id: number;
    };
    query?: never;
    url: '/resources/{id}';
};

export type GetResourcesByIdErrors = {
    /**
     * invalid id
     */
    400: string;
    /**
     * resource not found
     */
    404: string;
    /**
     * internal error
     */
    500: string;
};

export type GetResourcesByIdError = GetResourcesByIdErrors[keyof GetResourcesByIdErrors];

export type GetResourcesByIdResponses = {
    /**
     * OK
     */
    200: ResourcesResourceJsonResponseDto;
};

export type GetResourcesByIdResponse = GetResourcesByIdResponses[keyof GetResourcesByIdResponses];

export type PutResourcesByIdData = {
    /**
     * Updated resource object
     */
    body: ResourcesUpdateResourceRequestDto;
    path: {
        /**
         * Resource ID
         */
        id: number;
    };
    query?: never;
    url: '/resources/{id}';
};

export type PutResourcesByIdErrors = {
    /**
     * invalid request
     */
    400: string;
    /**
     * template not found
     */
    404: string;
    /**
     * internal error
     */
    500: string;
};

export type PutResourcesByIdError = PutResourcesByIdErrors[keyof PutResourcesByIdErrors];

export type PutResourcesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates';
};

export type GetTemplatesErrors = {
    /**
     * internal error
     */
    500: string;
};

export type GetTemplatesError = GetTemplatesErrors[keyof GetTemplatesErrors];

export type GetTemplatesResponses = {
    /**
     * OK
     */
    200: Array<TemplatesTemplateListJsonResponseDto>;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type PostTemplatesData = {
    /**
     * Template object
     */
    body: TemplatesCreateTemplateRequestDto;
    path?: never;
    query?: never;
    url: '/templates';
};

export type PostTemplatesErrors = {
    /**
     * invalid request
     */
    400: string;
};

export type PostTemplatesError = PostTemplatesErrors[keyof PostTemplatesErrors];

export type PostTemplatesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteTemplatesByIdData = {
    body?: never;
    path: {
        /**
         * Template ID
         */
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type DeleteTemplatesByIdErrors = {
    /**
     * invalid id
     */
    400: string;
    /**
     * template not found
     */
    404: string;
    /**
     * internal error
     */
    500: string;
};

export type DeleteTemplatesByIdError = DeleteTemplatesByIdErrors[keyof DeleteTemplatesByIdErrors];

export type DeleteTemplatesByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetTemplatesByIdData = {
    body?: never;
    path: {
        /**
         * Template ID
         */
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type GetTemplatesByIdErrors = {
    /**
     * invalid id
     */
    400: string;
    /**
     * template not found
     */
    404: string;
    /**
     * internal error
     */
    500: string;
};

export type GetTemplatesByIdError = GetTemplatesByIdErrors[keyof GetTemplatesByIdErrors];

export type GetTemplatesByIdResponses = {
    /**
     * OK
     */
    200: TemplatesTemplateJsonResponseDto;
};

export type GetTemplatesByIdResponse = GetTemplatesByIdResponses[keyof GetTemplatesByIdResponses];

export type PutTemplatesByIdData = {
    /**
     * Updated template object
     */
    body: TemplatesUpdateTemplateRequestDto;
    path: {
        /**
         * Template ID
         */
        id: number;
    };
    query?: never;
    url: '/templates/{id}';
};

export type PutTemplatesByIdErrors = {
    /**
     * invalid request
     */
    400: string;
    /**
     * template not found
     */
    404: string;
    /**
     * internal error
     */
    500: string;
};

export type PutTemplatesByIdError = PutTemplatesByIdErrors[keyof PutTemplatesByIdErrors];

export type PutTemplatesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
