// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zResourcesCreateResourceRequestDto = z.object({
    description: z.string().optional(),
    name: z.string(),
    price: z.int(),
    quantity: z.number(),
    unit: z.string()
});

export const zResourcesResourceJsonResponseDto = z.object({
    base_quantity: z.number(),
    base_unit: z.string(),
    created_at: z.string(),
    description: z.string(),
    id: z.int(),
    name: z.string(),
    price: z.int(),
    updated_at: z.string()
});

export const zResourcesUpdateResourceRequestDto = z.object({
    description: z.string().optional(),
    id: z.int(),
    name: z.string(),
    price: z.int(),
    quantity: z.number(),
    unit: z.string()
});

export const zTemplatesResourceRefDto = z.object({
    quantity: z.number(),
    resource_id: z.int(),
    unit: z.string()
});

export const zTemplatesResourceRefResponseDto = z.object({
    quantity: z.number(),
    resource_id: z.int(),
    unit: z.string()
});

export const zTemplatesStepDto = z.object({
    instructions: z.string(),
    name: z.string()
});

export const zTemplatesCreateTemplateRequestDto = z.object({
    description: z.string(),
    difficulty: z.int(),
    name: z.string(),
    quantity: z.number(),
    resources: z.array(zTemplatesResourceRefDto),
    steps: z.array(zTemplatesStepDto),
    unit: z.string()
});

export const zTemplatesStepJsonResponseDto = z.object({
    instructions: z.string(),
    name: z.string(),
    order: z.int()
});

export const zTemplatesTemplateJsonResponseDto = z.object({
    description: z.string(),
    difficulty: z.int(),
    id: z.int(),
    name: z.string(),
    quantity: z.number(),
    resources: z.array(zTemplatesResourceRefResponseDto),
    steps: z.array(zTemplatesStepJsonResponseDto),
    unit: z.string()
});

export const zTemplatesTemplateListJsonResponseDto = z.object({
    description: z.string(),
    id: z.int(),
    name: z.string()
});

export const zTemplatesUpdateTemplateRequestDto = z.object({
    description: z.string(),
    difficulty: z.int(),
    id: z.int(),
    name: z.string(),
    quantity: z.number(),
    resources: z.array(zTemplatesResourceRefDto),
    steps: z.array(zTemplatesStepDto),
    unit: z.string()
});

/**
 * OK
 */
export const zGetResourcesResponse = z.array(zResourcesResourceJsonResponseDto);

/**
 * Resource object
 */
export const zPostResourcesBody = zResourcesCreateResourceRequestDto;

export const zDeleteResourcesByIdPath = z.object({
    id: z.int()
});

export const zGetResourcesByIdPath = z.object({
    id: z.int()
});

/**
 * OK
 */
export const zGetResourcesByIdResponse = zResourcesResourceJsonResponseDto;

/**
 * Updated resource object
 */
export const zPutResourcesByIdBody = zResourcesUpdateResourceRequestDto;

export const zPutResourcesByIdPath = z.object({
    id: z.int()
});

/**
 * OK
 */
export const zGetTemplatesResponse = z.array(zTemplatesTemplateListJsonResponseDto);

/**
 * Template object
 */
export const zPostTemplatesBody = zTemplatesCreateTemplateRequestDto;

export const zDeleteTemplatesByIdPath = z.object({
    id: z.int()
});

export const zGetTemplatesByIdPath = z.object({
    id: z.int()
});

/**
 * OK
 */
export const zGetTemplatesByIdResponse = zTemplatesTemplateJsonResponseDto;

/**
 * Updated template object
 */
export const zPutTemplatesByIdBody = zTemplatesUpdateTemplateRequestDto;

export const zPutTemplatesByIdPath = z.object({
    id: z.int()
});
